apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
  labels:
    app: postgres
    chart: postgres-0.1.0
    release: my-release
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      release: my-release
  template:
    metadata:
      labels:
        app: postgres
        release: my-release
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.password }}"