apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ include "postgres.name" . }}
    chart: {{ include "postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
      nodePort: {{ .Values.service.nodePort }}  # Use the nodePort value from values.yaml
  selector:
    app: {{ include "postgres.name" . }}
    release: {{ .Release.Name }}