apiVersion: v1
kind: Service
metadata:
  name: my-postgres
  labels:
    app: postgres
    chart: postgres-0.1.0
    release: my-release
    heritage: Helm
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgres
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: postgres
    release: my-release