# helm/nginx/values.yaml
echo:
  image: "hashicorp/http-echo"
  tag: "latest"
  service:
    type: NodePort
    port: 5678
    nodePort: 30008  # Use a valid NodePort in the range 30000-32767
  args:
    - "-text=Hello, world!"
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "256Mi"